spring:
  cloud:
    alicloud:
      access-key: LTAI5t5ZBiEYocB7qkRRRvkd
      secret-key: CB5M5aJdkp6dQYYfVBM41kx1nH5EQy
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: qhmall-aurora

