spring:
  cloud:
    alicloud:
      access-key: LTAI5tC9bY6W6CYfa4gA1JJR
      secret-key: Weh7IhKk2l6BkACKSwKBnfafJ6qJPq
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: qhmall-aurora
      sms:
        host: https://fesms.market.alicloudapi.com
        path: /sms/
        skin: 1
        sign: 175622
        appcode: b0563c23aff8428c97a54d4f7f9e28e5

    sentinel:
      transport:
        dashboard: localhost:8333

management:
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  sentinel:
    enabled: true

