spring:
  cloud:
    nacos:
    alicloud:
      sms:
        host: https://fesms.market.alicloudapi.com
        path: /sms/
        skin: 1
        sign: 175622
        appcode: b0563c23aff8428c97a54d4f7f9e28e5
  #      access-key: LTAI4FwvfjSycd1APnuG9bjj
  #      secret-key: O6xaxyiWfSIitcOkSuK27ju4hXT5Hl
  #      oss:
  #        endpoint: oss-cn-beijing.aliyuncs.com
  #        bucket: qhmall-hello



