spring:
  task:
    scheduling:
      pool:
        size: 5
    execution:
      pool:
        core-size: 5
        max-size: 50

  redis:
    host: 192.168.174.130
    port: 6379

  session:
    store-type: redis

  rabbitmq:
    host: 192.168.174.130
    virtual-host: /

  thymeleaf:
    cache: false

  cloud:
    sentinel:
      transport:
        dashboard: 192.168.174.130:8858  # 控制台的安装位置
        port: 8719 # 与sentinel单独连接的端口
        client-ip: 192.168.3.1

management:
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  sentinel:
    enabled: true
