spring:
  cloud:
    gateway:
      routes:
        - id: product_route
          uri: lb://qhmall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: order_route
          uri: lb://qhmall-order
          predicates:
            - Path=/api/order/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: coupon_route
          uri: lb://qhmall-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: member_route
          uri: lb://qhmall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: ware_route
          uri: lb://qhmall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: third_party_route
          uri: lb://qhmall-third-party
          predicates:
            - Path=/api/third-party/**
          filters:
            - RewritePath=/api/third-party/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://qhmall-backend
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/qhmall-backend/$\{segment}

#        - id: qhmall_host_route # 要放在后面
#          uri: lb://qhmall-product
#          predicates:
#            - Host=qhmall.com, item.qhmall.com
#
#        - id: qhmall_search_route
#          uri: lb://qhmall-search
#          predicates:
#            - Host=search.qhmall.com
#
#        - id: qhmall_auth_route
#          uri: lb://qhmall-auth-server
#          predicates:
#            - Host=auth.qhmall.com
#
#        - id: qhmall_cart_route
#          uri: lb://qhmall-cart
#          predicates:
#            - Host=cart.qhmall.com
#
#        - id: qhmall_order_route
#          uri: lb://qhmall-order
#          predicates:
#            - Host=order.qhmall.com
#
#        - id: qhmall_member_route
#          uri: lb://qhmall-member
#          predicates:
#            - Host=member.qhmall.com
#
#        - id: qhmall_seckill_route
#          uri: lb://qhmall-seckill
#          predicates:
#            - Host=seckill.qhmall.com

      ## http://localhost:88/api/captcha.jpg   http://localhost:8888/qhmall-backend/captcha.jpg
      ## http://localhost:88/api/product/category/list/tree http://localhost:10000/product/category/list/tree

