spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.174.130:3306/qhmall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  thymeleaf:
    cache: false

  redis:
    host: 192.168.174.130
    port: 6379

  cache:
    type: redis
    redis:
      time-to-live: 3600000  # 过期时间
      #      key-prefix: CACHE_     # key前缀
      use-key-prefix: true  # 是否使用写入redis前缀
      cache-null-values: true # 是否缓存空值，防止缓存穿透

  session:
    store-type: redis

  cloud:
    sentinel:
      transport:
        dashboard: 192.168.174.130:8858  # 控制台的安装位置
        port: 8719 # 与sentinel单独连接的端口
        client-ip: 192.168.3.1
  #  zipkin:
  #    base-url: http://192.168.174.130:9411/ #Zipkin服务器地址
  #    discovery-client-enabled: false #关闭服务发现，否则SpringCloud会把Zipkin的url当作服务名称
  #    sender:
  #      type: web #设置使用http的方式传输数据
  #  sleuth:
  #    sampler:
  #      probability: 1 #设置抽样采集率为100%，默认为10%

management:
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  sentinel:
    enabled: true

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    com.qh.qhmall: debug #生产环境建议关闭


#配置线程池
qhmall:
  thread:
    coreSize: 20
    maxSize: 200
    keepAliveTime: 10



