server:
  port: 40000

spring:
  #  cloud:
  #    sentinel:
  #      transport:
  #        #配置sentinel dashboard地址
  #        dashboard: 192.168.174.130:8080
  redis:
    port: 6379
    host: 192.168.174.130

  cloud:
    sentinel:
      transport:
        dashboard: 192.168.174.130:8858  # 控制台的安装位置
        port: 8719 # 与sentinel单独连接的端口
        client-ip: 192.168.3.1

management:
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  sentinel:
    enabled: true

#配置线程池
qhmall:
  thread:
    coreSize: 20
    maxSize: 200
    keepAliveTime: 10



