spring:
  application:
    name: qhmall-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.174.130:8848

  thymeleaf:
    cache: false

  redis:
    port: 6379
    host: 192.168.174.130

  session:
    store-type: redis
