spring:
  thymeleaf:
    cache: false
  redis:
    port: 6379
    host: 192.168.174.130
  session:
    store-type: redis

  cloud:
    sentinel:
      transport:
        dashboard: 192.168.174.130:8858  # 控制台的安装位置
        port: 8719 # 与sentinel单独连接的端口
        client-ip: 192.168.3.1


management:
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  sentinel:
    enabled: true

logging:
  level:
    com.qh.qhmall.search.service: debug
